name: Build & Publish Laneway
run-name: Build version ${{ github.ref_name }}
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run all tests
        run: bun run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Clean deps
        run: rm -rf node_modules && rm -rf bun.lock

      - name: Install dependencies (with cross-platform native modules)
        run: bun install --os="*" --cpu="*" --force

      - name: Build macOS (arm64)
        run: bun run build:mac:arm

      - name: Build macOS (x64)
        run: bun run build:mac:x64

      - name: Build Ubuntu (arm64)
        run: bun run build:ubuntu:arm

      - name: Build Ubuntu (x64)
        run: bun run build:ubuntu:x64

      - name: Build Windows (arm64)
        run: bun run build:windows:arm

      - name: Build Windows (x64)
        run: bun run build:windows:x64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: laneway-binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download Artifacts
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          name: laneway-binaries
          path: dist/

      - name: Get Tag name
        id: vars
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: List files
        run: ls -laR dist

      # Generate GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{steps.download-artifact.outputs.download-path}}/*
          body: |
            **Laneway – Version ${{ github.ref_name }}**
            For detailed changes in this version, see the automatically generated notes.
          generate_release_notes: true
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Publish to NPM
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Publish Platform Packages
        run: bun run scripts/publish-packages.js
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Publish to NPM Registry
        run: npm publish
        env:
          NPM_CONFIG_PROVENANCE: true
